Update README.md
omarbelkady/Linux pull request #2
Opened 2020-08-27 04:57 UTC by alanngo

learn shell

2020-08-27 13:25 UTC, omarbelkady requested changes

2020-08-27 13:25 UTC, omarbelkady commented on README.md
> +root@omarbelkady:~$ echo "Omar 56837 74355"
NO echo "63527 56837 6342!"

2020-08-27 23:27 UTC, alanngo commented on README.md
> +root@omarbelkady:~$ echo "Omar 56837 74355"
but you 56837 74355

2020-08-28 01:30 UTC, omarbelkady commented on README.md
> +root@omarbelkady:~$ echo "Omar 56837 74355"
HELL NO

2020-08-28 02:45 UTC, closed without merging

2020-09-21 05:58 UTC, alanngo commented on README.md
> +root@omarbelkady:~$ echo "Omar 56837 74355"
echo "chromebooks suck"

2020-09-21 11:11 UTC, omarbelkady commented on README.md
> +root@omarbelkady:~$ echo "Omar 56837 74355"
echo "56837 47 2 2-56837"